import React, { useState } from 'react';
import { useZxing } from 'react-zxing';
import './QRCodeScanner.css';

function QRCodeScanner({ onQRCodeDetected, onClose }) {
  const [error, setError] = useState('');
  const [success, setSuccess] = useState(false);
  const [scanData, setScanData] = useState(null);
  
  const { ref } = useZxing({
    onDecodeResult(result) {
      try {
        // Try to parse the QR code content as JSON
        const reminderData = JSON.parse(result.getText());
        setScanData(reminderData);
        setSuccess(true);
        
        // Briefly show the success message before adding to list
        setTimeout(() => {
          onQRCodeDetected(reminderData);
        }, 800);
      } catch (err) {
        setError('Invalid QR code format. The QR code does not contain valid reminder data.');
      }
    },
    onError(error) {
      setError(`Error scanning: ${error.message}`);
    },
    constraints: {
      video: {
        facingMode: 'environment', // Use the back camera if available
        width: { ideal: 1280 },
        height: { ideal: 720 }
      }
    },
    timeBetweenDecodingAttempts: 300,
    formats: ['qrcode'], // Focus only on QR codes for better performance
  });

  return (
    <div className="qr-scanner-container">
      <div className="qr-scanner-header">
        <h3>Scan Reminder QR Code</h3>
        <button className="close-button" onClick={onClose}>×</button>
      </div>
      
      {error && (
        <div className="error-message">
          {error}
          <button onClick={() => setError('')}>×</button>
        </div>
      )}
      
      {success ? (
        <div className="success-message">
          <div className="success-icon">✓</div>
          <div className="success-text">
            <p>QR Code Successfully Scanned!</p>
            <p className="success-details">Adding "{scanData?.title}" to your reminders...</p>
          </div>
        </div>
      ) : (
        <>
          <div className="video-container">
            <video ref={ref} className="scanner-video" />
            <div className="scanner-overlay">
              <div className="scanner-target"></div>
            </div>
          </div>
          
          <div className="scanner-instructions">
            <p>Position the QR code inside the frame to scan</p>
            <p className="scanner-note">The QR code should contain reminder data generated by this app</p>
            <p className="scanner-tip">Make sure you have good lighting and hold the camera steady</p>
          </div>
        </>
      )}
    </div>
  );
}

export default QRCodeScanner; 